### ISSUE TITLE
no gettiing push in release mode 

### ISSUE THREAD

**Issue by syrakozz** [twilio/voice-quickstart-server-node#12]
i put a certificate for production in twilio but im not getting the push 
the error in logs is >> Pushing to this topic is not allowed
am i doing it wrong ?

**Comment by bobiechen-twilio** [comment]
Hi @syrakozz 

Could you please provide more information so we can help you debug the issue?
- What is the platform (Android or iOS) that you are having trouble receiving notifications?
- What is the error code and description that you are seeing in your developer console?

Thanks,
-bobie

**Comment by syrakozz** [comment]
sure, the platform is IOS
Error - 52143  - The push notification was rejected by APNs
Error -  52134 - Invalid APNs device token

**Comment by bobiechen-twilio** [comment]
Thanks for providing additional info.
It seems like the Push Credential SIDs of the sandbox environment and production environment are mixed and used with the wrong environments. The Push Credential SID used for the production environment should only be used for production version of the iOS app. You can follow [the instructions](https://github.com/twilio/voice-quickstart-objc#8-create-a-push-credential-with-your-voip-service-certificate) for setting up the incoming capability for your app.

Let me know if this helps.
-bobie

**Comment by bobiechen-twilio** [comment]
Hi @syrakozz 
By the way, when you said `Pushing to this topic is not allowed`, what was the error you were seeing? or was it in the detailed descriptions of the error that you saw in the console?

**Comment by syrakozz** [comment]
i was seeing this 
Error - 52143
The push notification was rejected by APNs


bindingType | "apn"
-- | --
primaryCorrelationId | "CA8e731cd4125a8f318c6c0d5371a4844b"
bindingSid | "BS42dbff3c0d30ffd49d3ca378b22634eb"
providerMessageId | "c28810fc-1a29-c38a-0f20-3dd11bead942"
requestId | "RQac2a9b606d4d9d7a6278bc448dbda808"
notificationSid | "NTe77ab87f1fbfb1dc5ca3c9e5697ba8a5"
module | "APNSBA"
description | "Pushing to this topic is not allowed."
isPassthrough | "false"
deliverySid | "DA22a9a02a0ff8b9925134092c259ca069"
fromReference | "CR7264c40cbe67ae89aed885ce060285d9"

**Comment by bobiechen-twilio** [comment]
Thanks for the update @syrakozz.
Please check if you are using the right Push Credential SID for the environment.

**Comment by syrakozz** [comment]
i regenerate the certificate now , still not getting push , but in the error logs im only getting 
52134 - Invalid APNs device token

**Comment by bobiechen-twilio** [comment]
Hi @syrakozz 

Since this is an iOS specific issue, could you please go to the [Voice iOS quickstart repo](https://github.com/twilio/voice-quickstart-objc) and open a new ticket so we can resume the debugging there?

Thanks.
-bobie
