### ISSUE TITLE
http://localhost:3000/ not working

### ISSUE THREAD

**Issue by girubhai** [twilio/voice-quickstart-server-node#15]
I did following steps to run server as given in readme.md :
1. clone project from https://github.com/twilio/voice-quickstart-server-node.git in **Intellij IDEA** IDE.
2. Edit value of ACCOUNT_SID, API_KEY and API_KEY_SECRET values in **.env.example** file.
3. Did run `cp .env.example .env` in terminal
4. run `npm install` in terminal
5. run `node` in terminal 
6. visit http://localhost:3000/
 
but its not connecting to localhost ?

**Comment by bobiechen-twilio** [comment]
@girubhai 

Please run `node .`
This should work.

Cheers,
-bobie
