### ISSUE TITLE
`dial.client(to)` logs `not a number` in console

### ISSUE THREAD

**Issue by hr-danielavram** [twilio/voice-quickstart-server-node#19]
I am trying to make some VoIP calls between two iOS devices as instructed here: https://github.com/twilio/voice-quickstart-ios. But for some strange reason they're not working. The log in the Twilio Dashboard -> Programmable Voice -> Call Logs says "No Answer" under the Status column. This is the log:

_CALL SID
CA17a52df521cc6670786e32a567292eca
DATE
09:11:22 UTC 2020-06-09
START TIME
09:11:22 UTC 2020-06-09
END TIME
09:11:22 UTC 2020-06-09
DURATION
0 sec
COST
—
PARENT CALL SID
CAbff5d7db2de94c7663539037920444dd
FROM
client:quick_start
TO
client:iPad
DIRECTION
Outgoing Dial
TYPE
Client
STATUS
No Answer_

Also, the server logs (to Terminal) look like this:

_Token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTS2Q5MDM0NWMxNDY4NTYyODI5ZGM5ODQ5MjI0MGE2ZDYwLTE1OTE2OTM4NzMiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJpUGhvbmUiLCJ2b2ljZSI6eyJpbmNvbWluZyI6eyJhbGxvdyI6dHJ1ZX0sIm91dGdvaW5nIjp7ImFwcGxpY2F0aW9uX3NpZCI6IkFQMzBiOGY2MWEwZTdjM2M5NjlmNTYzYzg3OTE3ZmVmMTkifSwicHVzaF9jcmVkZW50aWFsX3NpZCI6IkNSYTcyMWM5ZDkwMWQzODE0NGUxOGRiMDMzZmU3ZmJhOTIifX0sImlhdCI6MTU5MTY5Mzg3MywiZXhwIjoxNTkxNjk3NDczLCJpc3MiOiJTS2Q5MDM0NWMxNDY4NTYyODI5ZGM5ODQ5MjI0MGE2ZDYwIiwic3ViIjoiQUMwYzVhYWJiOWU1ZmQ1M2I2ZmQ5YTY5NDk3OGVlYzRiYiJ9.27YcxRZs80y1fRjZmojWgIwB8sR_j6r9zU9L42iJnvQ
not a number
Dialing client iPad
`Response:<?xml version="1.0" encoding="UTF-8"?><Response><Dial callerId="client:quick_start"><Client>iPad</Client></Dial></Response>`_

**Comment by bobiechen-twilio** [comment]
Hi @hr-danielavram 

From the Call SID you provided, it seems that under your account there is not client registered with the identity `iPad`, therefore the child call ended with No Answer. Can you please take a look at the callee client and make sure you have all the necessary elements (Push Credential SID, correct client identity) in your access token while registering the mobile client?

Thanks,
-bobie

**Comment by hr-danielavram** [comment]
Thanks. That was it. 🙂
