### ISSUE TITLE
Update an ongoing twilio client to client voice call

### ISSUE THREAD

**Issue by Ome27** [twilio/voice-quickstart-server-node#22]
Using twiml dial client library to initiate a call, working fine. Have added status call back events receiving callbacks. Now i just want to add new twiml <say> to the different call back statuses like busy,no-answer. 

What i found it is 
https://www.twilio.com/docs/voice/api/call-resource#update-a-call-resource
But this is using client.calls where as i am using twmil dial. How when i tried to use this 

https://www.twilio.com/docs/voice/api/call-resource?code-sample=code-create-a-call-resource-with-twiml&code-language=Node.js&code-sdk-version=3.x

The from was not set to client name.

**Comment by bobiechen-twilio** [comment]
Hi @Ome27 

For Twilio API and TwiML specific question, please contact [Twilio Support](https://support.twilio.com/hc/en-us) and our developer experience experts can provide better assistance to help you build the desired application behavior.
